### ISSUE TITLE
Exposing metrics port and endpoint

### ISSUE THREAD

**Issue by debMan** [openshift/vertical-pod-autoscaler-operator#142]
There are three endpoints for these components that would be nice to expose and scrape by Prometheus:
- vpa-admission-plugin: tcp/8944
- vpa-updater: tcp/8943
- vpa-recommender: tcp/8942

**Comment by rgordill** [comment]
They are already exposed upstream: https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/pkg/utils/metrics/metrics.go
