### ISSUE TITLE
Monitoring DeploymentConfig failed

### ISSUE THREAD

**Issue by jimmyjones2** [openshift/vertical-pod-autoscaler-operator#29]
I tried this with a Deployment and it worked, but errored with a DeploymentConfig. Should they be supported too?

**Comment by CurryWurry** [comment]
same issue here, looks like it is not supported. 

`    message: 'Cannot read targetRef. Reason: Unhandled targetRef apps.openshift.io/v1
      / DeploymentConfig / web-deployment, last error deploymentconfigs.apps.openshift.io
     "web-deployment" is forbidden: User "system:serviceaccount:openshift-vertical-pod-autoscaler:vpa-recommender"
      cannot get resource "deploymentconfigs/scale" in API group "apps.openshift.io"
      in the namespace "x"'
`
The 4.5 documentations mentions DeploymentConfig however...
