### ISSUE TITLE
4.6 fails to install operator

### ISSUE THREAD

**Issue by adrianchifor** [openshift/vertical-pod-autoscaler-operator#47]
Getting CreateContainerConfigError when VPA operator tries to come up (verticalpodautoscaler.4.6.0-202011041933.p0) on 4.6.5 cluster
```
Error: container has runAsNonRoot and image will run as root
```

Probably from this https://github.com/openshift/vertical-pod-autoscaler-operator/blob/b9bae5ffd1c2d29c4eea424a14c642d519ec9611/install/03_deployment.yaml#L51

`USER 65534` is likely missing from Dockerfile

**Comment by uberspot** [comment]
Bump

**Comment by adrianchifor** [comment]
RH doesn't care as long as it's not raised as an RFE or bug with support, will close here.
